services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft_server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "24w26a"
      TYPE: "VANILLA"      # This must be VANILLA even for snapshots!
      MEMORY: "3G"
    volumes:
      - ./minecraft-data:/data
    restart: unless-stopped