services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft_server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "LATEST"
      TYPE: "VANILLA"      # This MUST be VANILLA to fetch official snapshots
      MEMORY: "3G"
    volumes:
      - ./minecraft-data:/data
    restart: unless-stopped