name: 🔴 Stop Minecraft Server

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

# Ensure this block is present here too
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::513249876311:role/GithubActionsWorkflowRole
          aws-region: us-east-2

      - name: Gracefully Shut Down Docker via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd ~/minecraft-server
            docker-compose down

      - name: Power Down EC2 Instance
        run: |
          aws ec2 stop-instances --instance-ids ${{ secrets.AWS_EC2_INSTANCE_ID }}
